'''
Question 2 – Selenium IDE Export
Using Selenium IDE, create a test case that:
1. Opens a browser and navigates to https://example.com/login
2. Enters username and password
3. Clicks the login button
4. Validates the successful login message
'''


# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TC04():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_TC004(self):
        self.driver.get("https://the-internet.herokuapp.com/login")
        self.driver.set_window_size(833, 645)
        self.driver.find_element(By.ID, "username").click()
        self.driver.find_element(By.ID, "username").send_keys("whytocare")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("Pass@123")
        self.driver.find_element(By.CSS_SELECTOR, ".fa").click()